# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.20.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
- repo: local
  hooks:
    - id: format
      name: "Format (gofumpt)"
      entry: "./scripts/format.sh"
      language: script
      types: [go]
    - id: lint
      name: "Lint (golangci-lint)"
      entry: "./scripts/lint.sh"
      language: script
      types: [go]
      pass_filenames: false
