name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up
      uses: actions/setup-go@v5
    -
      name: Lint
      uses: golangci/golangci-lint-action@v6.1.0
    -
      name: Build
      run: make build
    -
      name: Test
      run: make test
    -
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: gms1/go-project-template
